language: php

php:
  - 7.4
  - 8.0

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: "royopa@gmail.com"

matrix:
  fast_finish: true
